In [1]:
import json
from Day5CompanyBrochure.RelevantLinks import getRelevantLinks
from Day5CompanyBrochure.WebsiteContent import getWebsiteContent
from Day5CompanyBrochure.BrochureContent import getBrochureContent
from Day5CompanyBrochure.Brochure import getBrochure

In [2]:
brochure = getBrochure('https://edwarddonner.com/',company_name='Ed Donner')

selecting relevant links from https://edwarddonner.com/ by calling gpt_oss

{
    "links": [
        {
            "type": "home page",
            "url": "https://edwarddonner.com/"
        },
        {
            "type": "about page",
            "url": "https://edwarddonner.com/about-me-and-about-nebula/"
        },
        {
            "type": "skills showcase",
            "url": "https://edwarddonner.com/proficient/"
        },
        {
            "type": "service offering",
            "url": "https://edwarddonner.com/outsmart/"
        },
        {
            "type": "product page",
            "url": "https://nebula.io/?utm_source=ed&utm_medium=referral"
        },
        {
            "type": "LinkedIn profile",
            "url": "https://www.linkedin.com/in/eddonner/"
        },
        {
            "type": "Twitter profile",
            "url": "https://twitter.com/edwarddonner"
        }
    ]
}

Found 7 relevant links

**Ed Donner – AI Engineer, Educator, Entrepreneur**
*Co‑Founder & CTO of Nebula.io*

---

## **Company Overview**

Ed Donner is a seasoned AI leader whose mission is simple yet profound: **Help people discover their true potential and pursue their reason for being.**
- **Nebula.io** – A generative‑AI powered recruiting platform that matches talent to roles *without* keywords.  Using a patented model, it delivers higher accuracy, faster throughput, and a superior user experience for both recruiters and candidates.
- **Mission‑Driven Technology** – Leveraging the concept of Ikigai, Nebula’s tools help people find roles that provide deep fulfillment and career satisfaction, thereby raising overall human prosperity.
- **Innovation & Growth** – Started as untapt (acquired 2021), continues to expand through AI‑centric products, educational content, and community engagement.

---

## **Products & Services**

### 1. **Nebula.io – AI‑Powered Recruiting**
| Feature | Benefit |
|---------|---------|
| **Zero‑Keyword Matching** | Cuts screening time from hours to minutes, dramatically boosting efficiency. |
| **Patented AI Model** | Higher precision and relevance than industry baselines. |
| **Free Trial** | Experience the platform risk‑free and discover its value before scaling. |

### 2. **AI Curriculum & Training**
Ed’s hands‑on courses bring industry‑leading AI knowledge to learners worldwide.
- **Udemy Best‑Seller**: Over **400 000 students** across 190 countries.
- **Course Topics**
  - *AI Coder: Vibe Coder to Agentic Engineer* – Feb 17 2026
  - *AI Builder with n8n – Create Agents & Voice Agents* – Jan 4 2026
  - *AI Engineering MLOps Track – Deploy AI to Production* – Sep 15 2025
  - *AI in Production – Gen‑AI & Agentic AI on AWS at Scale* – Sep 15 2025
- **Full Curriculum** – Accessible via the *AI Curriculum* section on the Ed Donner site.

### 3. **Engagement & Community**

| Tool | Experience |
|------|------------|
| **Connect Four** | Interactive LLM showdown to test AI model skills in real time. |
| **Outsmart Arena** | A battle environment where LLMs compete in diplomacy and cunning. |
| **Blog & Insight Posts** | Regular thought‑leadership pieces on AI, automation, and personal development. |

---

## **Investor Highlights**

- **Untapt Acquisition** – Ed’s flagship startup *untapt* was acquired by a prominent venture‑backed company in 2021, underscoring his proven ability to build & scale technology that attracts strategic investment.
- **Funding & Scale** – Nebula.io is backed by high‑growth investors who share Ed’s vision of redefining talent acquisition.
- **Patent Portfolio** – Nebula’s proprietary AI matching algorithm is a defensible asset, opening pathways for licensing and strategic partnerships.

*(If you’re an investor interested in the next wave of AI‑empowered recruitment, Nebula.io offers an opportunity to join a company positioned for high impact and rapid scale.)*

---

## **Careers & Culture**

- **People‑First Philosophy** – At Nebula.io, employees are valued as *human assets* and *creative problem solvers*.
- **Growth Mindset** – Continuous learning is baked into the culture; internal AI bootcamps and external training options are standard practice.
- **Diverse & Inclusive** – Team reflects a wide range of backgrounds, reinforcing Nebula’s commitment to matching talent with the right roles worldwide.
- **Flexible Work** – Remote‑first policy, flexible hours, and a results‑driven environment foster work‑life harmony.
- **Mission‑Driven Projects** – Every contribution directly supports the company’s larger goal of enhancing global human prosperity through better employment outcomes.

*Join us to build the future of hiring, while growing your own career and making a measurable difference in people’s lives.*

---

## **Thought Leadership & Influence**

- **Public Speaking** – Regular speaker at industry conferences on LLMs, agents, and AI ethics.
- **Podcast & Social Media** – Shares insights on Hacker News, Twitter, LinkedIn, and own blog.
- **Music & Creativity** – Amateur electronic music production illustrates a holistic approach to creativity and tech.

*Ed’s curiosity and passion for LLMs inspire not just code, but an entire community of learners and innovators.*

---

## **Get In Touch**

- **Email**: *ed@edwarddonner.com*
- **Website**: [edwarddonner.com](https://edwarddonner.com/)
- **LinkedIn**: [Ed Donner](https://www.linkedin.com/in/eddonner/)
- **Twitter**: [@edwarddonner](https://twitter.com/edwarddonner)
- **Facebook**: [Ed Donner](https://www.facebook.com/edward.donner.52)

---

### **Why Choose Ed Donner & Nebula.io?**

- **Proven Expertise** – From founding *untapt* to orchestrating a global AI curriculum.
- **Innovative Technology** – Patented models and zero‑keyword matching set a new industry standard.
- **Community & Impact** – Empowering millions through training and better career matches.
- **Future‑Ready** – Scaling on AWS, leveraging LLMs, and exploring agentic AI to stay ahead of the curve.

---

*Embark on a journey where AI meets purpose. Whether you’re a student looking to master AI, a company seeking talent, or an investor chasing the next big breakthrough, Ed Donner and Nebula.io are your trusted partners.*

In [3]:
print(brochure)

**Ed Donner – AI Engineer, Educator, Entrepreneur**
*Co‑Founder & CTO of Nebula.io*

---

## **Company Overview**

Ed Donner is a seasoned AI leader whose mission is simple yet profound: **Help people discover their true potential and pursue their reason for being.**
- **Nebula.io** – A generative‑AI powered recruiting platform that matches talent to roles *without* keywords.  Using a patented model, it delivers higher accuracy, faster throughput, and a superior user experience for both recruiters and candidates.
- **Mission‑Driven Technology** – Leveraging the concept of Ikigai, Nebula’s tools help people find roles that provide deep fulfillment and career satisfaction, thereby raising overall human prosperity.
- **Innovation & Growth** – Started as untapt (acquired 2021), continues to expand through AI‑centric products, educational content, and community engagement.

---

## **Products & Services**

### 1. **Nebula.io – AI‑Powered Recruiting**
| Feature | Benefit |
|---------|---------|
| **Zero‑Keyword Matching** | Cuts screening time from hours to minutes, dramatically boosting efficiency. |
| **Patented AI Model** | Higher precision and relevance than industry baselines. |
| **Free Trial** | Experience the platform risk‑free and discover its value before scaling. |

### 2. **AI Curriculum & Training**
Ed’s hands‑on courses bring industry‑leading AI knowledge to learners worldwide.
- **Udemy Best‑Seller**: Over **400 000 students** across 190 countries.
- **Course Topics**
  - *AI Coder: Vibe Coder to Agentic Engineer* – Feb 17 2026
  - *AI Builder with n8n – Create Agents & Voice Agents* – Jan 4 2026
  - *AI Engineering MLOps Track – Deploy AI to Production* – Sep 15 2025
  - *AI in Production – Gen‑AI & Agentic AI on AWS at Scale* – Sep 15 2025
- **Full Curriculum** – Accessible via the *AI Curriculum* section on the Ed Donner site.

### 3. **Engagement & Community**

| Tool | Experience |
|------|------------|
| **Connect Four** | Interactive LLM showdown to test AI model skills in real time. |
| **Outsmart Arena** | A battle environment where LLMs compete in diplomacy and cunning. |
| **Blog & Insight Posts** | Regular thought‑leadership pieces on AI, automation, and personal development. |

---

## **Investor Highlights**

- **Untapt Acquisition** – Ed’s flagship startup *untapt* was acquired by a prominent venture‑backed company in 2021, underscoring his proven ability to build & scale technology that attracts strategic investment.
- **Funding & Scale** – Nebula.io is backed by high‑growth investors who share Ed’s vision of redefining talent acquisition.
- **Patent Portfolio** – Nebula’s proprietary AI matching algorithm is a defensible asset, opening pathways for licensing and strategic partnerships.

*(If you’re an investor interested in the next wave of AI‑empowered recruitment, Nebula.io offers an opportunity to join a company positioned for high impact and rapid scale.)*

---

## **Careers & Culture**

- **People‑First Philosophy** – At Nebula.io, employees are valued as *human assets* and *creative problem solvers*.
- **Growth Mindset** – Continuous learning is baked into the culture; internal AI bootcamps and external training options are standard practice.
- **Diverse & Inclusive** – Team reflects a wide range of backgrounds, reinforcing Nebula’s commitment to matching talent with the right roles worldwide.
- **Flexible Work** – Remote‑first policy, flexible hours, and a results‑driven environment foster work‑life harmony.
- **Mission‑Driven Projects** – Every contribution directly supports the company’s larger goal of enhancing global human prosperity through better employment outcomes.

*Join us to build the future of hiring, while growing your own career and making a measurable difference in people’s lives.*

---

## **Thought Leadership & Influence**

- **Public Speaking** – Regular speaker at industry conferences on LLMs, agents, and AI ethics.
- **Podcast & Social Media** – Shares insights on Hacker News, Twitter, LinkedIn, and own blog.
- **Music & Creativity** – Amateur electronic music production illustrates a holistic approach to creativity and tech.

*Ed’s curiosity and passion for LLMs inspire not just code, but an entire community of learners and innovators.*

---

## **Get In Touch**

- **Email**: *ed@edwarddonner.com*
- **Website**: [edwarddonner.com](https://edwarddonner.com/)
- **LinkedIn**: [Ed Donner](https://www.linkedin.com/in/eddonner/)
- **Twitter**: [@edwarddonner](https://twitter.com/edwarddonner)
- **Facebook**: [Ed Donner](https://www.facebook.com/edward.donner.52)

---

### **Why Choose Ed Donner & Nebula.io?**

- **Proven Expertise** – From founding *untapt* to orchestrating a global AI curriculum.
- **Innovative Technology** – Patented models and zero‑keyword matching set a new industry standard.
- **Community & Impact** – Empowering millions through training and better career matches.
- **Future‑Ready** – Scaling on AWS, leveraging LLMs, and exploring agentic AI to stay ahead of the curve.

---

*Embark on a journey where AI meets purpose. Whether you’re a student looking to master AI, a company seeking talent, or an investor chasing the next big breakthrough, Ed Donner and Nebula.io are your trusted partners.*

In [2]:
content = getWebsiteContent('https://edwarddonner.com/')
content

'Home - Edward Donner Home AI Curriculum Proficient AI Engineer Connect Four Outsmart An arena that pits LLMs against each other in a battle of diplomacy and deviousness About Posts Well, hi there. I’m Ed. I like writing code and experimenting with LLMs, and hopefully you’re here because you do too. I also enjoy amateur electronic music production ( very amateur) and losing myself in Hacker News , nodding my head sagely to things I only half understand. I’m the co-founder and CTO of Nebula.io . We’re applying AI to a field where it can make a massive, positive impact: helping people discover their potential and pursue their reason for being. I’m previously the founder and CEO of AI startup untapt, acquired in 2021 . I will happily drone on for hours about LLMs to anyone in my vicinity. My friends got fed up with my impromptu lectures, and convinced me to make some Udemy courses. To my total joy (and shock) they’ve become best-selling, top-rated courses, with 400,000 enrolled across 190 countries. The full curriculum is here . If you’re visiting from one of my courses – I’m super grateful! February 17, 2026 AI Coder: Vibe Coder to Agentic Engineer – RESOURCES January 4, 2026 AI Builder with n8n – Create Agents and Voice Agents – RESOURCES September 15, 2025 AI Engineering MLOps Track – Deploy AI to Production – RESOURCES May 28, 2025 Which order to take the AI courses? Navigation Home AI Curriculum Proficient AI Engineer Connect Four Outsmart An arena that pits LLMs against each other in a battle of diplomacy and deviousness About Posts Get in touch ed [at] edwarddonner [dot] com www.edwarddonner.com Follow me LinkedIn Twitter Facebook'

In [3]:
links = getRelevantLinks('https://edwarddonner.com/')

selecting relevant links from https://edwarddonner.com/ by calling gpt_oss

{
  "links": [
    {"type":"home page","url":"https://edwarddonner.com/"},
    {"type":"about page","url":"https://edwarddonner.com/about-me-and-about-nebula/"},
    {"type":"blog","url":"https://edwarddonner.com/posts/"},
    {"type":"curriculum","url":"https://edwarddonner.com/curriculum/"},
    {"type":"Nebula product","url":"https://nebula.io/?utm_source=ed&utm_medium=referral"},
    {"type":"proficient project","url":"https://edwarddonner.com/proficient/"},
    {"type":"outsmart project","url":"https://edwarddonner.com/outsmart/"},
    {"type":"LinkedIn","url":"https://www.linkedin.com/in/eddonner/"},
    {"type":"Twitter","url":"https://twitter.com/edwarddonner"}
  ]
}

Found 9 relevant links

In [4]:
print(links)

{'links': [{'type': 'home page', 'url': 'https://edwarddonner.com/'}, {'type': 'about page', 'url': 'https://edwarddonner.com/about-me-and-about-nebula/'}, {'type': 'blog', 'url': 'https://edwarddonner.com/posts/'}, {'type': 'curriculum', 'url': 'https://edwarddonner.com/curriculum/'}, {'type': 'Nebula product', 'url': 'https://nebula.io/?utm_source=ed&utm_medium=referral'}, {'type': 'proficient project', 'url': 'https://edwarddonner.com/proficient/'}, {'type': 'outsmart project', 'url': 'https://edwarddonner.com/outsmart/'}, {'type': 'LinkedIn', 'url': 'https://www.linkedin.com/in/eddonner/'}, {'type': 'Twitter', 'url': 'https://twitter.com/edwarddonner'}]}

In [5]:
type(links)

dict

In [6]:
links['links']

[{'type': 'home page', 'url': 'https://edwarddonner.com/'},
 {'type': 'about page',
  'url': 'https://edwarddonner.com/about-me-and-about-nebula/'},
 {'type': 'blog', 'url': 'https://edwarddonner.com/posts/'},
 {'type': 'curriculum', 'url': 'https://edwarddonner.com/curriculum/'},
 {'type': 'Nebula product',
  'url': 'https://nebula.io/?utm_source=ed&utm_medium=referral'},
 {'type': 'proficient project', 'url': 'https://edwarddonner.com/proficient/'},
 {'type': 'outsmart project', 'url': 'https://edwarddonner.com/outsmart/'},
 {'type': 'LinkedIn', 'url': 'https://www.linkedin.com/in/eddonner/'},
 {'type': 'Twitter', 'url': 'https://twitter.com/edwarddonner'}]

In [7]:
import pandas as pd

df = pd.DataFrame(links['links'])

In [8]:
df

                 type                                                url
0           home page                          https://edwarddonner.com/
1          about page  https://edwarddonner.com/about-me-and-about-ne...
2                blog                    https://edwarddonner.com/posts/
3          curriculum               https://edwarddonner.com/curriculum/
4      Nebula product  https://nebula.io/?utm_source=ed&utm_medium=re...
5  proficient project               https://edwarddonner.com/proficient/
6    outsmart project                 https://edwarddonner.com/outsmart/
7            LinkedIn              https://www.linkedin.com/in/eddonner/
8             Twitter                   https://twitter.com/edwarddonner

In [9]:
hugging_links = getRelevantLinks('https://huggingface.co/')

selecting relevant links from https://huggingface.co/ by calling gpt_oss

{
  "links": [
    {"type": "home page", "url": "https://huggingface.co/"},
    {"type": "about page", "url": "https://huggingface.co/brand"},
    {"type": "documentation", "url": "https://huggingface.co/docs"},
    {"type": "model hub", "url": "https://huggingface.co/models"},
    {"type": "dataset hub", "url": "https://huggingface.co/datasets"},
    {"type": "space platform", "url": "https://huggingface.co/spaces"},
    {"type": "blog", "url": "https://huggingface.co/blog"},
    {"type": "pricing", "url": "https://huggingface.co/pricing"},
    {"type": "enterprise solutions", "url": "https://huggingface.co/enterprise"},
    {"type": "learning resources", "url": "https://huggingface.co/learn"},
    {"type": "community forum", "url": "https://discuss.huggingface.co"},
    {"type": "status page", "url": "https://status.huggingface.co/"},
    {"type": "github repository", "url": "https://github.com/huggingface"},
    {"type": "linkedin page", "url": "https://www.linkedin.com/company/huggingface/"},
    {"type": "twitter page", "url": "https://twitter.com/huggingface"},
    {"type": "discord community", "url": "https://huggingface.co/join/discord"},
    {"type": "chat demo", "url": "https://huggingface.co/chat"},
    {"type": "inference models", "url": "https://huggingface.co/inference/models"},
    {"type": "pricing – Spaces", "url": "https://huggingface.co/pricing#spaces"},
    {"type": "pricing – Endpoints", "url": "https://huggingface.co/pricing#endpoints"}
  ]
}

Found 20 relevant links

In [10]:
print(hugging_links)

{'links': [{'type': 'home page', 'url': 'https://huggingface.co/'}, {'type': 'about page', 'url': 'https://huggingface.co/brand'}, {'type': 'documentation', 'url': 'https://huggingface.co/docs'}, {'type': 'model hub', 'url': 'https://huggingface.co/models'}, {'type': 'dataset hub', 'url': 'https://huggingface.co/datasets'}, {'type': 'space platform', 'url': 'https://huggingface.co/spaces'}, {'type': 'blog', 'url': 'https://huggingface.co/blog'}, {'type': 'pricing', 'url': 'https://huggingface.co/pricing'}, {'type': 'enterprise solutions', 'url': 'https://huggingface.co/enterprise'}, {'type': 'learning resources', 'url': 'https://huggingface.co/learn'}, {'type': 'community forum', 'url': 'https://discuss.huggingface.co'}, {'type': 'status page', 'url': 'https://status.huggingface.co/'}, {'type': 'github repository', 'url': 'https://github.com/huggingface'}, {'type': 'linkedin page', 'url': 'https://www.linkedin.com/company/huggingface/'}, {'type': 'twitter page', 'url': 'https://twitter.com/huggingface'}, {'type': 'discord community', 'url': 'https://huggingface.co/join/discord'}, {'type': 'chat demo', 'url': 'https://huggingface.co/chat'}, {'type': 'inference models', 'url': 'https://huggingface.co/inference/models'}, {'type': 'pricing – Spaces', 'url': 'https://huggingface.co/pricing#spaces'}, {'type': 'pricing – Endpoints', 'url': 'https://huggingface.co/pricing#endpoints'}]}

In [11]:
df = pd.DataFrame(hugging_links['links'])
df

                    type                                            url
0              home page                        https://huggingface.co/
1             about page                   https://huggingface.co/brand
2          documentation                    https://huggingface.co/docs
3              model hub                  https://huggingface.co/models
4            dataset hub                https://huggingface.co/datasets
5         space platform                  https://huggingface.co/spaces
6                   blog                    https://huggingface.co/blog
7                pricing                 https://huggingface.co/pricing
8   enterprise solutions              https://huggingface.co/enterprise
9     learning resources                   https://huggingface.co/learn
10       community forum                 https://discuss.huggingface.co
11           status page                 https://status.huggingface.co/
12     github repository                 https://github.com/huggingface
13         linkedin page  https://www.linkedin.com/company/huggingface/
14          twitter page                https://twitter.com/huggingface
15     discord community            https://huggingface.co/join/discord
16             chat demo                    https://huggingface.co/chat
17      inference models        https://huggingface.co/inference/models
18      pricing – Spaces          https://huggingface.co/pricing#spaces
19   pricing – Endpoints       https://huggingface.co/pricing#endpoints